<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listHasValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmdbXSB0aGVMaXN0ID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KHBpcGVs
aW5lQ3Vyc29yLCAidGhlTGlzdCIpOw0KU3RyaW5nIHRoZVZhbHVlID0gSURhdGFVdGlsLmdldFN0
cmluZyhwaXBlbGluZUN1cnNvciwgInRoZVZhbHVlIik7DQoNCmJvb2xlYW4gX2Jvb2wgPSBmYWxz
ZTsNCg0KaWYgKHRoZUxpc3QgIT0gbnVsbCAmJiB0aGVWYWx1ZSAhPSBudWxsKSB7DQogICAgZm9y
IChTdHJpbmcgcyA6IHRoZUxpc3QpIHsNCiAgICAgICAgaWYgKHRoZVZhbHVlLmVxdWFscyhzKSkg
eyAgLy8gdGhlVmFsdWUgaXMgZ3VhcmFudGVlZCBub24tbnVsbCBoZXJlDQogICAgICAgICAgICBf
Ym9vbCA9IHRydWU7DQogICAgICAgICAgICBicmVhazsgLy8gY2FuIHN0b3AgZWFybHkNCiAgICAg
ICAgfQ0KICAgIH0NCn0NCg0KSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImhhc1ZhbHVl
IiwgQm9vbGVhbi52YWx1ZU9mKF9ib29sKSk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
